inkscape --file ./svgs/Logo_FC_Bayern_M%C3%BCnchen.svg --export-width 100 --export-height 100 --export-png ./pngs/Logo_FC_Bayern_M%C3%BCnchen.png
inkscape --file ./svgs/HSV-Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/HSV-Logo.png
inkscape --file ./svgs/Logo_FC_Augsburg.svg --export-width 100 --export-height 100 --export-png ./pngs/Logo_FC_Augsburg.png
inkscape --file ./svgs/Hertha_BSC_Logo_2012.svg --export-width 100 --export-height 100 --export-png ./pngs/Hertha_BSC_Logo_2012.png
inkscape --file ./svgs/Bayer_04_Leverkusen_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Bayer_04_Leverkusen_Logo.png
inkscape --file ./svgs/Logo_TSG_Hoffenheim.svg --export-width 100 --export-height 100 --export-png ./pngs/Logo_TSG_Hoffenheim.png
inkscape --file ./svgs/Svdarmstadt98.svg --export-width 100 --export-height 100 --export-png ./pngs/Svdarmstadt98.png
inkscape --file ./svgs/Hannover_96_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Hannover_96_Logo.png
inkscape --file ./svgs/FSV_Mainz_05_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/FSV_Mainz_05_Logo.png
inkscape --file ./svgs/FC-Ingolstadt_logo.svg --export-width 100 --export-height 100 --export-png ./pngs/FC-Ingolstadt_logo.png
inkscape --file ./svgs/SV-Werder-Bremen-Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/SV-Werder-Bremen-Logo.png
inkscape --file ./svgs/FC_Schalke_04_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/FC_Schalke_04_Logo.png
inkscape --file ./svgs/Borussia_Dortmund_logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Borussia_Dortmund_logo.png
inkscape --file ./svgs/Borussia_M%C3%B6nchengladbach_logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Borussia_M%C3%B6nchengladbach_logo.png
inkscape --file ./svgs/VfL_Wolfsburg_Logo_wei%C3%9F.svg --export-width 100 --export-height 100 --export-png ./pngs/VfL_Wolfsburg_Logo_wei%C3%9F.png
inkscape --file ./svgs/Eintracht_Frankfurt_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Eintracht_Frankfurt_Logo.png
inkscape --file ./svgs/VfB_Stuttgart_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/VfB_Stuttgart_Logo.png
inkscape --file ./svgs/1._FC_K%C3%B6ln.svg --export-width 100 --export-height 100 --export-png ./pngs/1._FC_K%C3%B6ln.png
inkscape --file ./svgs/Msv_duisburg%28neu%29.svg --export-width 100 --export-height 100 --export-png ./pngs/Msv_duisburg%28neu%29.png
inkscape --file ./svgs/Logo_1_FC_Kaiserslautern.svg --export-width 100 --export-height 100 --export-png ./pngs/Logo_1_FC_Kaiserslautern.png
inkscape --file ./svgs/Logo_Eintracht_Braunschweig.svg --export-width 100 --export-height 100 --export-png ./pngs/Logo_Eintracht_Braunschweig.png
inkscape --file ./svgs/SV_Sandhausen.svg --export-width 100 --export-height 100 --export-png ./pngs/SV_Sandhausen.png
inkscape --file ./svgs/SC-Freiburg_Logo-neu.svg --export-width 100 --export-height 100 --export-png ./pngs/SC-Freiburg_Logo-neu.png
inkscape --file ./svgs/1._FC_N%C3%BCrnberg_logo.svg --export-width 100 --export-height 100 --export-png ./pngs/1._FC_N%C3%BCrnberg_logo.png
inkscape --file ./svgs/FSV_Frankfurt_1899.svg --export-width 100 --export-height 100 --export-png ./pngs/FSV_Frankfurt_1899.png
inkscape --file ./svgs/RB_Leipzig_2010_logo.svg --export-width 100 --export-height 100 --export-png ./pngs/RB_Leipzig_2010_logo.png
inkscape --file ./svgs/SpVgg_Greuther_F%C3%BCrth_logo.svg --export-width 100 --export-height 100 --export-png ./pngs/SpVgg_Greuther_F%C3%BCrth_logo.png
inkscape --file ./svgs/Karlsruher_SC_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Karlsruher_SC_Logo.png
inkscape --file ./svgs/1._FC_Heidenheim_1846.svg --export-width 100 --export-height 100 --export-png ./pngs/1._FC_Heidenheim_1846.png
inkscape --file ./svgs/TSV_1860_M%C3%BCnchen.svg --export-width 100 --export-height 100 --export-png ./pngs/TSV_1860_M%C3%BCnchen.png
inkscape --file ./svgs/SC_Paderborn_07_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/SC_Paderborn_07_Logo.png
inkscape --file ./svgs/Logo_VfL_Bochum.svg --export-width 100 --export-height 100 --export-png ./pngs/Logo_VfL_Bochum.png
inkscape --file ./svgs/Logo_FC_St_Pauli.svg --export-width 100 --export-height 100 --export-png ./pngs/Logo_FC_St_Pauli.png
inkscape --file ./svgs/Logo_Arminia_Bielefeld.svg --export-width 100 --export-height 100 --export-png ./pngs/Logo_Arminia_Bielefeld.png
inkscape --file ./svgs/1._FC_Union_Berlin.svg --export-width 100 --export-height 100 --export-png ./pngs/1._FC_Union_Berlin.png
inkscape --file ./svgs/Fortuna_D%C3%BCsseldorf.svg --export-width 100 --export-height 100 --export-png ./pngs/Fortuna_D%C3%BCsseldorf.png
inkscape --file ./svgs/LOSC_Lille_Crest_2012.png --export-width 100 --export-height 100 --export-png ./pngs/LOSC_Lille_Crest_2012.png
inkscape --file ./svgs/Paris_Saint-Germain_%28seit_2013%29.gif --export-width 100 --export-height 100 --export-png ./pngs/Paris_Saint-Germain_%28seit_2013%29.png
inkscape --file ./svgs/ES_Troyes_AC.svg --export-width 100 --export-height 100 --export-png ./pngs/ES_Troyes_AC.png
inkscape --file ./svgs/Gaz%C3%A9lec_Ajaccio_logo.png --export-width 100 --export-height 100 --export-png ./pngs/Gaz%C3%A9lec_Ajaccio_logo.png
inkscape --file ./svgs/Olympique_Marseille_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Olympique_Marseille_Logo.png
inkscape --file ./svgs/LogoSmc2013.png --export-width 100 --export-height 100 --export-png ./pngs/LogoSmc2013.png
inkscape --file ./svgs/OGC_Nice_logo.png --export-width 100 --export-height 100 --export-png ./pngs/OGC_Nice_logo.png
inkscape --file ./svgs/AS_Monaco.svg --export-width 100 --export-height 100 --export-png ./pngs/AS_Monaco.png
inkscape --file ./svgs/FC_Nantes_%28seit_2008%29.svg --export-width 100 --export-height 100 --export-png ./pngs/FC_Nantes_%28seit_2008%29.png
inkscape --file ./svgs/EA_Guingamp_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/EA_Guingamp_Logo.png
inkscape --file ./svgs/HSC_Montpellier_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/HSC_Montpellier_Logo.png
inkscape --file ./svgs/SCO_Angers.svg --export-width 100 --export-height 100 --export-png ./pngs/SCO_Angers.png
inkscape --file ./svgs/SC_Bastia.svg --export-width 100 --export-height 100 --export-png ./pngs/SC_Bastia.png
inkscape --file ./svgs/Stade_Rennais_Football_Club.svg --export-width 100 --export-height 100 --export-png ./pngs/Stade_Rennais_Football_Club.png
inkscape --file ./svgs/Girondins_Bordeaux_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Girondins_Bordeaux_Logo.png
inkscape --file ./svgs/Stade_Reims_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Stade_Reims_Logo.png
inkscape --file ./svgs/FC_Toulouse_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/FC_Toulouse_Logo.png
inkscape --file ./svgs/AS_Saint-Etienne_%28aktuell%29.svg --export-width 100 --export-height 100 --export-png ./pngs/AS_Saint-Etienne_%28aktuell%29.png
inkscape --file ./svgs/Olympique_Lyon.svg --export-width 100 --export-height 100 --export-png ./pngs/Olympique_Lyon.png
inkscape --file ./svgs/FC_Lorient_neu.png --export-width 100 --export-height 100 --export-png ./pngs/FC_Lorient_neu.png
inkscape --file ./svgs/AC_Ajaccio.svg --export-width 100 --export-height 100 --export-png ./pngs/AC_Ajaccio.png
inkscape --file ./svgs/FCO_Dijon.svg --export-width 100 --export-height 100 --export-png ./pngs/FCO_Dijon.png
inkscape --file ./svgs/Logo_ParisFC_2011.png --export-width 100 --export-height 100 --export-png ./pngs/Logo_ParisFC_2011.png
inkscape --file ./svgs/Stade_Laval.svg --export-width 100 --export-height 100 --export-png ./pngs/Stade_Laval.png
inkscape --file ./svgs/Chamois_Niort_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Chamois_Niort_Logo.png
inkscape --file ./svgs/Valenciennes_AFC_%282008%29.svg --export-width 100 --export-height 100 --export-png ./pngs/Valenciennes_AFC_%282008%29.png
inkscape --file ./svgs/Olympique_Nimes.svg --export-width 100 --export-height 100 --export-png ./pngs/Olympique_Nimes.png
inkscape --file ./svgs/Evian_Thonon_Gaillard.svg --export-width 100 --export-height 100 --export-png ./pngs/Evian_Thonon_Gaillard.png
inkscape --file ./svgs/Logo_RedStarFC.png --export-width 100 --export-height 100 --export-png ./pngs/Logo_RedStarFC.png
inkscape --file ./svgs/US_Cr%C3%A9teil.svg --export-width 100 --export-height 100 --export-png ./pngs/US_Cr%C3%A9teil.png
inkscape --file ./svgs/Clermont_Foot_Auvergne.svg --export-width 100 --export-height 100 --export-png ./pngs/Clermont_Foot_Auvergne.png
inkscape --file ./svgs/FC_Sochaux_Logo_2010.svg --export-width 100 --export-height 100 --export-png ./pngs/FC_Sochaux_Logo_2010.png
inkscape --file ./svgs/File:Football_club_Bourg-P%C3%A9ronnas.svg --export-width 100 --export-height 100 --export-png ./pngs/File:Football_club_Bourg-P%C3%A9ronnas.png                                                                                                                                                       
inkscape --file ./svgs/Le_Havre_AC.svg --export-width 100 --export-height 100 --export-png ./pngs/Le_Havre_AC.png                                              
inkscape --file ./svgs/AJ_Auxerre.svg --export-width 100 --export-height 100 --export-png ./pngs/AJ_Auxerre.png                                                
inkscape --file ./svgs/Stade_Brestois_29.svg --export-width 100 --export-height 100 --export-png ./pngs/Stade_Brestois_29.png                                  
inkscape --file ./svgs/FC_Metz_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/FC_Metz_Logo.png                                            
inkscape --file ./svgs/RC_Lens_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/RC_Lens_Logo.png                                            
inkscape --file ./svgs/AS_Nancy_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/AS_Nancy_Logo.png                                          
inkscape --file ./svgs/FC_Tours.svg --export-width 100 --export-height 100 --export-png ./pngs/FC_Tours.png                                                    
inkscape --file ./svgs/Manchester_United_FC.svg --export-width 100 --export-height 100 --export-png ./pngs/Manchester_United_FC.png
inkscape --file ./svgs/Tottenham_Hotspur.svg --export-width 100 --export-height 100 --export-png ./pngs/Tottenham_Hotspur.png
inkscape --file ./svgs/Afc_bournemouth.svg --export-width 100 --export-height 100 --export-png ./pngs/Afc_bournemouth.png
inkscape --file ./svgs/Aston_Villa_logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Aston_Villa_logo.png
inkscape --file ./svgs/Everton_FC.svg --export-width 100 --export-height 100 --export-png ./pngs/Everton_FC.png
inkscape --file ./svgs/Watford.svg --export-width 100 --export-height 100 --export-png ./pngs/Watford.png
inkscape --file ./svgs/Leicester02.png --export-width 100 --export-height 100 --export-png ./pngs/Leicester02.png
inkscape --file ./svgs/AFC_Sunderland.svg --export-width 100 --export-height 100 --export-png ./pngs/AFC_Sunderland.png
inkscape --file ./svgs/Norwich_City.svg --export-width 100 --export-height 100 --export-png ./pngs/Norwich_City.png
inkscape --file ./svgs/Crystal_Palace_F.C._logo_%282013%29.png --export-width 100 --export-height 100 --export-png ./pngs/Crystal_Palace_F.C._logo_%282013%29.png
inkscape --file ./svgs/Chelsea_crest.svg --export-width 100 --export-height 100 --export-png ./pngs/Chelsea_crest.png
inkscape --file ./svgs/Swansea_City_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Swansea_City_Logo.png
inkscape --file ./svgs/Newcastle_United_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Newcastle_United_Logo.png
inkscape --file ./svgs/FC_Southampton.svg --export-width 100 --export-height 100 --export-png ./pngs/FC_Southampton.png
inkscape --file ./svgs/Arsenal_FC.svg --export-width 100 --export-height 100 --export-png ./pngs/Arsenal_FC.png
inkscape --file ./svgs/West_Ham_United_FC.svg --export-width 100 --export-height 100 --export-png ./pngs/West_Ham_United_FC.png
inkscape --file ./svgs/Stoke_City.svg --export-width 100 --export-height 100 --export-png ./pngs/Stoke_City.png
inkscape --file ./svgs/FC_Liverpool.svg --export-width 100 --export-height 100 --export-png ./pngs/FC_Liverpool.png
inkscape --file ./svgs/West_Bromwich_Albion.svg --export-width 100 --export-height 100 --export-png ./pngs/West_Bromwich_Albion.png
inkscape --file ./svgs/ManCity.svg --export-width 100 --export-height 100 --export-png ./pngs/ManCity.png
inkscape --file ./svgs/RC_Deportivo_La_Coru%C3%B1a_logo.svg --export-width 100 --export-height 100 --export-png ./pngs/RC_Deportivo_La_Coru%C3%B1a_logo.png
inkscape --file ./svgs/Real_Sociedad_San_Sebasti%C3%A1n.svg --export-width 100 --export-height 100 --export-png ./pngs/Real_Sociedad_San_Sebasti%C3%A1n.png
inkscape --file ./svgs/RCD_Espanyol_De_Barcelona.svg --export-width 100 --export-height 100 --export-png ./pngs/RCD_Espanyol_De_Barcelona.png
inkscape --file ./svgs/Getafe_CF.svg --export-width 100 --export-height 100 --export-png ./pngs/Getafe_CF.png
inkscape --file ./svgs/Atletico_Madrid_logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Atletico_Madrid_logo.png
inkscape --file ./svgs/UD_Las_Palmas_logo.svg --export-width 100 --export-height 100 --export-png ./pngs/UD_Las_Palmas_logo.png
inkscape --file ./svgs/FC_Valencia.svg --export-width 100 --export-height 100 --export-png ./pngs/FC_Valencia.png
inkscape --file ./svgs/FC_M%C3%A1laga.svg --export-width 100 --export-height 100 --export-png ./pngs/FC_M%C3%A1laga.png
inkscape --file ./svgs/Sevilla_cf_200px.png --export-width 100 --export-height 100 --export-png ./pngs/Sevilla_cf_200px.png
inkscape --file ./svgs/Athletic_Club_Bilbao.svg --export-width 100 --export-height 100 --export-png ./pngs/Athletic_Club_Bilbao.png
inkscape --file ./svgs/Fc_barcelona.svg --export-width 100 --export-height 100 --export-png ./pngs/Fc_barcelona.png
inkscape --file ./svgs/Real_Sporting_de_Gijon.svg --export-width 100 --export-height 100 --export-png ./pngs/Real_Sporting_de_Gijon.png
inkscape --file ./svgs/Real_Madrid_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Real_Madrid_Logo.png
inkscape --file ./svgs/Levante_ud.svg --export-width 100 --export-height 100 --export-png ./pngs/Levante_ud.png
inkscape --file ./svgs/Celta_Vigo.svg --export-width 100 --export-height 100 --export-png ./pngs/Celta_Vigo.png
inkscape --file ./svgs/Real_Betis.svg --export-width 100 --export-height 100 --export-png ./pngs/Real_Betis.png
inkscape --file ./svgs/Villarreal_CF_logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Villarreal_CF_logo.png
inkscape --file ./svgs/Granada_CF.svg --export-width 100 --export-height 100 --export-png ./pngs/Granada_CF.png
inkscape --file ./svgs/SD_Eibar_logo.svg --export-width 100 --export-height 100 --export-png ./pngs/SD_Eibar_logo.png
inkscape --file ./svgs/CD_Mirand%C3%A9s_logo.svg --export-width 100 --export-height 100 --export-png ./pngs/CD_Mirand%C3%A9s_logo.png
inkscape --file ./svgs/Real_zaragoza.svg --export-width 100 --export-height 100 --export-png ./pngs/Real_zaragoza.png
inkscape --file ./svgs/Real_Oviedo.svg --export-width 100 --export-height 100 --export-png ./pngs/Real_Oviedo.png
inkscape --file ./svgs/CD_Lugo_logo.svg --export-width 100 --export-height 100 --export-png ./pngs/CD_Lugo_logo.png
inkscape --file ./svgs/SD_Ponferradina_logo.svg --export-width 100 --export-height 100 --export-png ./pngs/SD_Ponferradina_logo.png
inkscape --file ./svgs/Elche_CF.svg --export-width 100 --export-height 100 --export-png ./pngs/Elche_CF.png
inkscape --file ./svgs/CD_Numancia_logo.svg --export-width 100 --export-height 100 --export-png ./pngs/CD_Numancia_logo.png
inkscape --file ./svgs/CD_Tenerife_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/CD_Tenerife_Logo.png
inkscape --file ./svgs/AD_Alcorc%C3%B3n_logo.svg --export-width 100 --export-height 100 --export-png ./pngs/AD_Alcorc%C3%B3n_logo.png
inkscape --file ./svgs/Rcd_mallorca.svg --export-width 100 --export-height 100 --export-png ./pngs/Rcd_mallorca.png
inkscape --file ./svgs/UE_Llagostera.png --export-width 100 --export-height 100 --export-png ./pngs/UE_Llagostera.png
inkscape --file ./svgs/Atletico_Osasuna.svg --export-width 100 --export-height 100 --export-png ./pngs/Atletico_Osasuna.png
inkscape --file ./svgs/Deportivo_Alaves_logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Deportivo_Alaves_logo.png
inkscape --file ./svgs/Union_Deportiva_Almeria.svg --export-width 100 --export-height 100 --export-png ./pngs/Union_Deportiva_Almeria.png
inkscape --file ./svgs/180px-Club_Deportivo_Legan%C3%A9s.png --export-width 100 --export-height 100 --export-png ./pngs/180px-Club_Deportivo_Legan%C3%A9s.png
inkscape --file ./svgs/Gimn%C3%A0stic_tarragona_200px.png --export-width 100 --export-height 100 --export-png ./pngs/Gimn%C3%A0stic_tarragona_200px.png
inkscape --file ./svgs/C%C3%B3rdoba_CF_logo.svg --export-width 100 --export-height 100 --export-png ./pngs/C%C3%B3rdoba_CF_logo.png
inkscape --file ./svgs/Real_Valladolid_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Real_Valladolid_Logo.png
inkscape --file ./svgs/150px-Athletic_Club_Bilbao.svg.png --export-width 100 --export-height 100 --export-png ./pngs/150px-Athletic_Club_Bilbao.svg.png
inkscape --file ./svgs/For_article_Girona_FC.svg --export-width 100 --export-height 100 --export-png ./pngs/For_article_Girona_FC.png
inkscape --file ./svgs/Hellas_Verona_1903_FC.svg --export-width 100 --export-height 100 --export-png ./pngs/Hellas_Verona_1903_FC.png
inkscape --file ./svgs/AS_Rom.svg --export-width 100 --export-height 100 --export-png ./pngs/AS_Rom.png
inkscape --file ./svgs/Juventus_Turin.svg --export-width 100 --export-height 100 --export-png ./pngs/Juventus_Turin.png
inkscape --file ./svgs/Udinese_Calcio.svg --export-width 100 --export-height 100 --export-png ./pngs/Udinese_Calcio.png
inkscape --file ./svgs/US_Palermo.svg --export-width 100 --export-height 100 --export-png ./pngs/US_Palermo.png
inkscape --file ./svgs/Genoa_CFC.svg --export-width 100 --export-height 100 --export-png ./pngs/Genoa_CFC.png
inkscape --file ./svgs/US_Sassuolo_Calcio.svg --export-width 100 --export-height 100 --export-png ./pngs/US_Sassuolo_Calcio.png
inkscape --file ./svgs/S.S.C._Napoli_logo.svg --export-width 100 --export-height 100 --export-png ./pngs/S.S.C._Napoli_logo.png
inkscape --file ./svgs/Sampdoria_Genua.svg --export-width 100 --export-height 100 --export-png ./pngs/Sampdoria_Genua.png
inkscape --file ./svgs/Carpi_FC.png --export-width 100 --export-height 100 --export-png ./pngs/Carpi_FC.png
inkscape --file ./svgs/500px-Lazio_Rom.svg.png --export-width 100 --export-height 100 --export-png ./pngs/500px-Lazio_Rom.svg.png
inkscape --file ./svgs/FC_Bologna.svg --export-width 100 --export-height 100 --export-png ./pngs/FC_Bologna.png
inkscape --file ./svgs/Logo_FC_Internazionale_Milano_2014.png --export-width 100 --export-height 100 --export-png ./pngs/Logo_FC_Internazionale_Milano_2014.png
inkscape --file ./svgs/Atalanta_BC.svg --export-width 100 --export-height 100 --export-png ./pngs/Atalanta_BC.png
inkscape --file ./svgs/Frosinonestemma.png --export-width 100 --export-height 100 --export-png ./pngs/Frosinonestemma.png
inkscape --file ./svgs/Torino_FC_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Torino_FC_Logo.png
inkscape --file ./svgs/AC_Florenz.svg --export-width 100 --export-height 100 --export-png ./pngs/AC_Florenz.png
inkscape --file ./svgs/AC_Mailand_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/AC_Mailand_Logo.png
inkscape --file ./svgs/Logo_FC_Empoli.svg --export-width 100 --export-height 100 --export-png ./pngs/Logo_FC_Empoli.png
inkscape --file ./svgs/AC_Chievo_Verona.svg --export-width 100 --export-height 100 --export-png ./pngs/AC_Chievo_Verona.png
inkscape --file ./svgs/Emblema_CD_Tondela.png --export-width 100 --export-height 100 --export-png ./pngs/Emblema_CD_Tondela.png
inkscape --file ./svgs/Logo_Sporting_Clube_de_Portugal_-_1930_-_1945.svg --export-width 100 --export-height 100 --export-png ./pngs/Logo_Sporting_Clube_de_Portugal_-_1930_-_1945.png
inkscape --file ./svgs/Belenenses_Lissabon.svg --export-width 100 --export-height 100 --export-png ./pngs/Belenenses_Lissabon.png
inkscape --file ./svgs/Rio_Ave_FC.svg --export-width 100 --export-height 100 --export-png ./pngs/Rio_Ave_FC.png
inkscape --file ./svgs/FC_Porto_1922-2005.svg --export-width 100 --export-height 100 --export-png ./pngs/FC_Porto_1922-2005.png
inkscape --file ./svgs/Vitoria_Guimaraes.svg --export-width 100 --export-height 100 --export-png ./pngs/Vitoria_Guimaraes.png
inkscape --file ./svgs/Vit%C3%B3ria_Set%C3%BAbal.svg --export-width 100 --export-height 100 --export-png ./pngs/Vit%C3%B3ria_Set%C3%BAbal.png
inkscape --file ./svgs/Boavista_F.C._logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Boavista_F.C._logo.png
inkscape --file ./svgs/UMadeira.png --export-width 100 --export-height 100 --export-png ./pngs/UMadeira.png
inkscape --file ./svgs/Mar%C3%ADtimo_Funchal.svg --export-width 100 --export-height 100 --export-png ./pngs/Mar%C3%ADtimo_Funchal.png
inkscape --file ./svgs/Logo_Moreirense.svg --export-width 100 --export-height 100 --export-png ./pngs/Logo_Moreirense.png
inkscape --file ./svgs/FC_Arouca.png --export-width 100 --export-height 100 --export-png ./pngs/FC_Arouca.png
inkscape --file ./svgs/Sporting_Clube_de_Braga.svg --export-width 100 --export-height 100 --export-png ./pngs/Sporting_Clube_de_Braga.png
inkscape --file ./svgs/Nacional_Funchal.svg --export-width 100 --export-height 100 --export-png ./pngs/Nacional_Funchal.png
inkscape --file ./svgs/Logo_Benfica_Lissabon.svg --export-width 100 --export-height 100 --export-png ./pngs/Logo_Benfica_Lissabon.png
inkscape --file ./svgs/GD_Estoril_Praia.svg --export-width 100 --export-height 100 --export-png ./pngs/GD_Estoril_Praia.png
inkscape --file ./svgs/FC_Pacos_de_Ferreira.svg --export-width 100 --export-height 100 --export-png ./pngs/FC_Pacos_de_Ferreira.png
inkscape --file ./svgs/Logo_Academica_de_Coimbra.svg --export-width 100 --export-height 100 --export-png ./pngs/Logo_Academica_de_Coimbra.png
inkscape --file ./svgs/FFC_Magdeburg.svg --export-width 100 --export-height 100 --export-png ./pngs/FFC_Magdeburg.png
inkscape --file ./svgs/Rot_Weiss_Erfurt_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Rot_Weiss_Erfurt_Logo.png
inkscape --file ./svgs/Logo_SV_Wehen_Wiesbaden.svg --export-width 100 --export-height 100 --export-png ./pngs/Logo_SV_Wehen_Wiesbaden.png
inkscape --file ./svgs/Kickers_Wurzburg.png --export-width 100 --export-height 100 --export-png ./pngs/Kickers_Wurzburg.png
inkscape --file ./svgs/FC_Hansa_Rostock.png --export-width 100 --export-height 100 --export-png ./pngs/FC_Hansa_Rostock.png
inkscape --file ./svgs/SV-Werder-Bremen-Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/SV-Werder-Bremen-Logo.png
inkscape --file ./svgs/Stuttgarter_Kickers.png --export-width 100 --export-height 100 --export-png ./pngs/Stuttgarter_Kickers.png
inkscape --file ./svgs/SC_Fortuna_Koln.png --export-width 100 --export-height 100 --export-png ./pngs/SC_Fortuna_Koln.png
inkscape --file ./svgs/SC_Preussen_Muenster_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/SC_Preussen_Muenster_Logo.png
inkscape --file ./svgs/SG_Sonnenhof.svg --export-width 100 --export-height 100 --export-png ./pngs/SG_Sonnenhof.png
inkscape --file ./svgs/Holstein_Kiel_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Holstein_Kiel_Logo.png
inkscape --file ./svgs/FSV_Mainz_05_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/FSV_Mainz_05_Logo.png
inkscape --file ./svgs/Fc_erzgebirge_aue.svg --export-width 100 --export-height 100 --export-png ./pngs/Fc_erzgebirge_aue.png
inkscape --file ./svgs/Logo_Vfl_Osnabrueck.svg --export-width 100 --export-height 100 --export-png ./pngs/Logo_Vfl_Osnabrueck.png
inkscape --file ./svgs/Logo_SG_Dynamo_Dresden_neu.svg --export-width 100 --export-height 100 --export-png ./pngs/Logo_SG_Dynamo_Dresden_neu.png
inkscape --file ./svgs/VfB_Stuttgart_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/VfB_Stuttgart_Logo.png
inkscape --file ./svgs/VfR_Aalen_Wappen.svg --export-width 100 --export-height 100 --export-png ./pngs/VfR_Aalen_Wappen.png
inkscape --file ./svgs/Chemnitzer_FC_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Chemnitzer_FC_Logo.png
inkscape --file ./svgs/Fcenergie.png --export-width 100 --export-height 100 --export-png ./pngs/Fcenergie.png
inkscape --file ./svgs/Hallescher_FC_Logo_2012.svg --export-width 100 --export-height 100 --export-png ./pngs/Hallescher_FC_Logo_2012.png
inkscape --file ./svgs/Roda_JC_Kerkrade_%282011%29.svg --export-width 100 --export-height 100 --export-png ./pngs/Roda_JC_Kerkrade_%282011%29.png
inkscape --file ./svgs/Heracles_Almelo.svg --export-width 100 --export-height 100 --export-png ./pngs/Heracles_Almelo.png
inkscape --file ./svgs/Logo_Feyenoord_Rotterdam.svg --export-width 100 --export-height 100 --export-png ./pngs/Logo_Feyenoord_Rotterdam.png
inkscape --file ./svgs/FC_Utrecht.svg --export-width 100 --export-height 100 --export-png ./pngs/FC_Utrecht.png
inkscape --file ./svgs/AZ_Alkmaar.svg --export-width 100 --export-height 100 --export-png ./pngs/AZ_Alkmaar.png
inkscape --file ./svgs/Ajax_Amsterdam.svg --export-width 100 --export-height 100 --export-png ./pngs/Ajax_Amsterdam.png
inkscape --file ./svgs/Willem_II_Tilburg.svg --export-width 100 --export-height 100 --export-png ./pngs/Willem_II_Tilburg.png
inkscape --file ./svgs/Vitesse_Arnheim.svg --export-width 100 --export-height 100 --export-png ./pngs/Vitesse_Arnheim.png
inkscape --file ./svgs/ADO_Den_Haag.svg --export-width 100 --export-height 100 --export-png ./pngs/ADO_Den_Haag.png
inkscape --file ./svgs/PSV_Eindhoven.svg --export-width 100 --export-height 100 --export-png ./pngs/PSV_Eindhoven.png
inkscape --file ./svgs/SC_Heerenveen.svg --export-width 100 --export-height 100 --export-png ./pngs/SC_Heerenveen.png
inkscape --file ./svgs/VBV_De_Graafschap_Doetinchem.svg --export-width 100 --export-height 100 --export-png ./pngs/VBV_De_Graafschap_Doetinchem.png
inkscape --file ./svgs/FC_Groningen.svg --export-width 100 --export-height 100 --export-png ./pngs/FC_Groningen.png
inkscape --file ./svgs/FC_Twente_Enschede_%28ab_2006%29.svg --export-width 100 --export-height 100 --export-png ./pngs/FC_Twente_Enschede_%28ab_2006%29.png
inkscape --file ./svgs/PEC_Zwolle_2012.svg --export-width 100 --export-height 100 --export-png ./pngs/PEC_Zwolle_2012.png
inkscape --file ./svgs/SC_Cambuur-Leeuwarden.svg --export-width 100 --export-height 100 --export-png ./pngs/SC_Cambuur-Leeuwarden.png
inkscape --file ./svgs/NEC_Nijmegen.svg --export-width 100 --export-height 100 --export-png ./pngs/NEC_Nijmegen.png
inkscape --file ./svgs/SBV_Excelsior_logo.png --export-width 100 --export-height 100 --export-png ./pngs/SBV_Excelsior_logo.png
inkscape --file ./svgs/Paris_Saint-Germain_%28seit_2013%29.gif --export-width 100 --export-height 100 --export-png ./pngs/Paris_Saint-Germain_%28seit_2013%29.png
inkscape --file ./svgs/Logo_Malm%C3%B6_FF.svg --export-width 100 --export-height 100 --export-png ./pngs/Logo_Malm%C3%B6_FF.png
inkscape --file ./svgs/Logo_Benfica_Lissabon.svg --export-width 100 --export-height 100 --export-png ./pngs/Logo_Benfica_Lissabon.png
inkscape --file ./svgs/FC_Astana_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/FC_Astana_Logo.png
inkscape --file ./svgs/Sevilla_cf_200px.png --export-width 100 --export-height 100 --export-png ./pngs/Sevilla_cf_200px.png
inkscape --file ./svgs/Borussia_M%C3%B6nchengladbach_logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Borussia_M%C3%B6nchengladbach_logo.png
inkscape --file ./svgs/ManCity.svg --export-width 100 --export-height 100 --export-png ./pngs/ManCity.png
inkscape --file ./svgs/Juventus_Turin.svg --export-width 100 --export-height 100 --export-png ./pngs/Juventus_Turin.png
inkscape --file ./svgs/Galatasaray_Sports_Club_Logo.png --export-width 100 --export-height 100 --export-png ./pngs/Galatasaray_Sports_Club_Logo.png
inkscape --file ./svgs/Atletico_Madrid_logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Atletico_Madrid_logo.png
inkscape --file ./svgs/VfL_Wolfsburg_Logo_wei%C3%9F.svg --export-width 100 --export-height 100 --export-png ./pngs/VfL_Wolfsburg_Logo_wei%C3%9F.png
inkscape --file ./svgs/CSKA_Moscow_logo.png --export-width 100 --export-height 100 --export-png ./pngs/CSKA_Moscow_logo.png
inkscape --file ./svgs/PSV_Eindhoven.svg --export-width 100 --export-height 100 --export-png ./pngs/PSV_Eindhoven.png
inkscape --file ./svgs/Manchester_United_FC.svg --export-width 100 --export-height 100 --export-png ./pngs/Manchester_United_FC.png
inkscape --file ./svgs/Real_Madrid_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Real_Madrid_Logo.png
inkscape --file ./svgs/FC_Shakhtar_Donetsk.png --export-width 100 --export-height 100 --export-png ./pngs/FC_Shakhtar_Donetsk.png
inkscape --file ./svgs/FC_Valencia.svg --export-width 100 --export-height 100 --export-png ./pngs/FC_Valencia.png
inkscape --file ./svgs/FC_Zenit_1_star_2015_logo.png --export-width 100 --export-height 100 --export-png ./pngs/FC_Zenit_1_star_2015_logo.png
inkscape --file ./svgs/FC_Dynamo_Kyiv_logo.png --export-width 100 --export-height 100 --export-png ./pngs/FC_Dynamo_Kyiv_logo.png
inkscape --file ./svgs/FC_Porto_1922-2005.svg --export-width 100 --export-height 100 --export-png ./pngs/FC_Porto_1922-2005.png
inkscape --file ./svgs/Chelsea_crest.svg --export-width 100 --export-height 100 --export-png ./pngs/Chelsea_crest.png
inkscape --file ./svgs/MTAFC_logo.png --export-width 100 --export-height 100 --export-png ./pngs/MTAFC_logo.png
inkscape --file ./svgs/Logo_Olympiakos_Pir%C3%A4us.svg --export-width 100 --export-height 100 --export-png ./pngs/Logo_Olympiakos_Pir%C3%A4us.png
inkscape --file ./svgs/Logo_FC_Bayern_M%C3%BCnchen.svg --export-width 100 --export-height 100 --export-png ./pngs/Logo_FC_Bayern_M%C3%BCnchen.png
inkscape --file ./svgs/Dinamo-Zagreb.png --export-width 100 --export-height 100 --export-png ./pngs/Dinamo-Zagreb.png
inkscape --file ./svgs/Arsenal_FC.svg --export-width 100 --export-height 100 --export-png ./pngs/Arsenal_FC.png
inkscape --file ./svgs/AS_Rom.svg --export-width 100 --export-height 100 --export-png ./pngs/AS_Rom.png
inkscape --file ./svgs/Fc_barcelona.svg --export-width 100 --export-height 100 --export-png ./pngs/Fc_barcelona.png
inkscape --file ./svgs/Bayer_04_Leverkusen_Logo.svg --export-width 100 --export-height 100 --export-png ./pngs/Bayer_04_Leverkusen_Logo.png
inkscape --file ./svgs/150px-Logo_BATE_Baryssau.svg.png --export-width 100 --export-height 100 --export-png ./pngs/150px-Logo_BATE_Baryssau.svg.png
inkscape --file ./svgs/KAA_Gent_logo.svg --export-width 100 --export-height 100 --export-png ./pngs/KAA_Gent_logo.png
inkscape --file ./svgs/Olympique_Lyon.svg --export-width 100 --export-height 100 --export-png ./pngs/Olympique_Lyon.png
